name: .NET

on:
  push:
    branches: [ master, sqlite3mc ]
  pull_request:
    branches: [ master, sqlite3mc ]

jobs:
  build:

    strategy:
      matrix:
        # TODO want macos-latest here too, but the build currently fails there
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: "SQLitePCL.raw"
    - uses: actions/checkout@v3
      with:
        repository: utelle/SQLite3MultipleCiphers-cb
        path: "cb"
    - name: "Set up Java: 11"
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Install workload ios
      run: dotnet workload install ios
    - name: Install workload maccatalyst
      run: dotnet workload install maccatalyst
    - name: Install workload android
      run: dotnet workload install android
    - name: Install workload tvos
      run: dotnet workload install tvos
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Install T4
      run: dotnet tool install --global dotnet-t4
    - name: Build
      run: |
        cd SQLitePCL.raw/build
        dotnet run
